# PyMEOP Config file, YAML
---
settings:
    probe_ip: 129.57.36.81
    meter_ip: 129.57.37.92
    siggen_ip: 129.57.37.95    #91
    lockin_ip: 129.57.37.101
    labjack_ip: 129.57.37.97
    scan_wait: 0.05              # seconds between running scan current change and read
    temp_scan_wait: 0.2         # seconds between temp change and read
    curr_scan_wait: 0.1         # seconds between curr change and read
    event_dir: 'data'
    log_dir: 'log'
    scan_x_axis: 'current'      # X-axis to use for scans, either "current" or "wavelength"
    scan_wave: False              # Do wavelengh reads for running scan?